spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
server:
  port: 0
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      warehouse:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
    instances:
      warehouse:
        base-config: default